### ISSUE TITLE
Function insertScript accepts an optional 3rd parameter, container

### ISSUE THREAD

**Issue by Helen-Mobify** [mobify/descript#4]
The inserted script is set to the same container as the `searchType` script's container. With the optional `container` parameter, we can inject a script at the order we want and in the container we choose. If `container` parameter is not specified, descript work as before.

Use case example:
1. There is a client script we need to replace at the same order
2. Move the client script in to another container, `ignore`, to maintain the order of the scripts
3. Inject our replacement scripts after the client scripts with `default` container

**Comment by scalvert** [comment]
I'm having a hard time understanding the above. Right now when you inject a script, you'll most likely want to inject it after another in the same container. So, the search type reflects this; you'd search for a script and inject it after, using the searched for script's container.

Can you clarify what you mean with all three above, as they aren't really clear to me.

**Comment by Helen-Mobify** [comment]
Summary of what was discussed offline.

The use case of this situation is very rare, in fact, it promotes anti-pattern where we are changing the source of the external scripts.

Closing this issue as **Will not implement**
